// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $ClientSide from "./routes/ClientSide.tsx";
import * as $ClientSideSearch from "./routes/ClientSideSearch.tsx";
import * as $ServerSide from "./routes/ServerSide.tsx";
import * as $ServerSideSearch from "./routes/ServerSideSearch.tsx";
import * as $WordPage from "./routes/WordPage.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $InputForm from "./islands/InputForm.tsx";
import * as $WordCSR from "./islands/WordCSR.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/ClientSide.tsx": $ClientSide,
    "./routes/ClientSideSearch.tsx": $ClientSideSearch,
    "./routes/ServerSide.tsx": $ServerSide,
    "./routes/ServerSideSearch.tsx": $ServerSideSearch,
    "./routes/WordPage.tsx": $WordPage,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/InputForm.tsx": $InputForm,
    "./islands/WordCSR.tsx": $WordCSR,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
